name: Call GeoIPS workflows triggered on PR close

on:
  # Triggers the workflow when pull request created and updated
  pull_request:
  workflow_dispatch:

jobs:
  print_run_flags:
    runs-on: ${{ vars.RUNNER }}
    steps:
      - name: Print run flags
        run: |
          echo "github.ref_name ${{ github.ref_name }}"
          echo "github.ref ${{ github.ref }}"
          echo "github.base_ref ${{ github.base_ref }}"
          echo "github.head_ref ${{ github.head_ref }}"
          echo "vars.RUNNER ${{ vars.RUNNER }}"
          echo "vars.RUNNER_DOCKERBUILD ${{ vars.RUNNER_DOCKERBUILD }}"
          echo "vars.RUNNER_DOCKERRUN ${{ vars.RUNNER_DOCKERRUN }}"
          echo "github.event.repository.default_branch ${{ github.event.repository.default_branch }}"
          echo "github.event.repository.name ${{ github.event.repository.name }}"
          echo "github.event.pull_request.merged ${{ github.event.pull_request.merged }}"
          echo "github.run_id ${{ github.run_id }}"
          echo "github.run_attempt ${{ github.run_attempt }}"
          echo "vars.USE_CONDA_FOR_ACTIONS ${{ vars.USE_CONDA_FOR_ACTIONS }}"
          echo "$GITHUB_CONTEXT"
          echo ${{ github.context }}

  set_variables:
    runs-on: ${{ vars.RUNNER }}
    env:
      CURR_REPO: ${{ github.event.repository.name }}
    outputs:
      # The name of the untagged docker images to be created by this workflow
      pr_was_merged: ${{ steps.set_pr_status.outputs.PR_WAS_MERGED }}
    steps:
      - name: Set the PR status
        id: set_pr_status
        run: |
          pr_was_merged=${{ github.event.pull_request.merged }}
          echo "$pr_was_merged"
          echo "PR_WAS_MERGED=$pr_was_merged"
          echo "PR_WAS_MERGED=$pr_was_merged" >> $GITHUB_ENV
          echo "PR_WAS_MERGED=$pr_was_merged" >> $GITHUB_OUTPUT

  call_on_closed_pr:
    permissions:
      pull-requests: write
      contents: write
    # You do not appear to be able to use variables in this "uses" field.
    uses: NRLMMD-GEOIPS/.github/.github/workflows/on-closed-pr.yaml@main
    needs: set_variables
    with:
      pr_was_merged: ${{ needs.set_variables.outputs.PR_WAS_MERGED }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
