$id: "bases.base"
title: "Base"
description: |
  The base for all YAML-based plugins. This should be used as a reference at the
  top of all yaml-based plugin schema.
type: object
required:
  - interface
  - family
  - metadata
properties:
  interface:
    type: string
  family:
    type: string
  metadata:
    type: object
    required: [name, short-description, long-description]
    properties:
      name:
        type: string
      short-description:
        type: string
      long-description:
        type: string
