$id: products.bases.product
type: object
required:
  - name
  # - spec
unevaluatedProperties: false
properties:
  name:
    $ref: bases.name
  docstring:
    $ref: bases.docstring
  family:
    $ref: bases.family
  product_defaults:
    $ref: bases.product_defaults

  spec:
    type: object
    # required:
    #   - source_name
    #   - variables
    properties:
      source_name:
        type: string
      variables:
        type: array
        minItems: 1
        items:
          type: string
oneOf:
  - required:
      - family
      - docstring
  - required:
      - product_defaults
