interface: "boundaries"
metadata:
  name: "default"
  family: "standard"
  short-description: "The default boundaries configuration"
  long-description:
    "All line types enabled. All colored red. 2px coastlines, 1px countries,
    0.5px states borders, and 0px rivers."
spec:
  coastlines:
    enabled: true
  countries:
    enabled: true
  states:
    enabled: true
  rivers:
    enabled: true

