"""Unit test module for testing workflow overrides.

NOTE: THIS MODULE WAS GENERATED BY AI.
"""

import pytest
from copy import deepcopy

from geoips.interfaces.yaml_based.workflows import workflows


@pytest.fixture
def sample_workflow():
    """Return a representative workflow dictionary."""
    return {
        "name": "dummy_workflow",
        "spec": {
            "steps": {
                "reader": {
                    "kind": "reader",
                    "arguments": {
                        "self_register": "HIGH",
                        "satellite_zenith_angle_cutoff": 70,
                    },
                },
                "algorithm": {
                    "kind": "algorithm",
                    "arguments": {
                        "output_units": "celsius",
                    },
                },
                "nested_workflow": {
                    "kind": "workflow",
                    "spec": {
                        "steps": {
                            "nested_algorithm": {
                                "kind": "algorithm",
                                "arguments": {
                                    "output_units": "celsius",
                                },
                            }
                        }
                    },
                },
            }
        },
        "test": {
            "globals": {
                "logging_level": "INFO",
            },
            "kinds": {
                "algorithms": {
                    "output_units": "kelvin",
                }
            },
            "steps": {
                "reader": {
                    "self_register": "LOW",
                }
            },
        },
    }


##########################################
#
# STRING-BASED OVERRIDE TESTS
#
##########################################


def test_set_nested():
    """Test setting nested dictionary values."""
    steps = {
        "reader": {
            "arguments": {
                "self_register": "HIGH",
            }
        }
    }

    result = workflows._set_nested(
        steps,
        "reader",
        [],
        "self_register",
        "LOW",
    )

    assert result["reader"]["arguments"]["self_register"] == "LOW"


def test_override_step(sample_workflow):
    """Test overriding a specific step."""
    override = {
        "step_id": "reader",
        "keys": [],
        "argument": "self_register",
        "value": "LOW",
    }

    steps = deepcopy(sample_workflow["spec"]["steps"])

    result = workflows._override_step(steps, override)

    assert result["reader"]["arguments"]["self_register"] == "LOW"


def test_override_kind(sample_workflow):
    """Test overriding all steps of a given kind."""
    override = {
        "kind": "algorithm",
        "argument": "output_units",
        "value": "kelvin",
    }

    steps = deepcopy(sample_workflow["spec"]["steps"])

    result = workflows._override_kind(steps, override)

    assert result["algorithm"]["arguments"]["output_units"] == "kelvin"


def test_override_global(sample_workflow):
    """Test overriding all matching global arguments."""
    override = {
        "argument": "satellite_zenith_angle_cutoff",
        "value": 80,
    }

    steps = deepcopy(sample_workflow["spec"]["steps"])

    result = workflows._override_global(steps, override)

    assert result["reader"]["arguments"]["satellite_zenith_angle_cutoff"] == 80


def test_override_workflow_string_format(sample_workflow):
    """Test applying all string-based overrides."""
    workflow = deepcopy(sample_workflow)

    goverrides = [
        {
            "argument": "satellite_zenith_angle_cutoff",
            "value": 85,
        }
    ]

    koverrides = [
        {
            "kind": "algorithms",
            "argument": "output_units",
            "value": "kelvin",
        }
    ]

    soverrides = [
        {
            "step_id": "reader",
            "keys": [],
            "argument": "self_register",
            "value": "LOW",
        }
    ]

    result = workflows._override_workflow_string_format(
        workflow,
        goverrides=goverrides,
        koverrides=koverrides,
        soverrides=soverrides,
    )

    steps = result["spec"]["steps"]

    assert steps["reader"]["arguments"]["self_register"] == "LOW"
    assert steps["reader"]["arguments"]["satellite_zenith_angle_cutoff"] == 85
    assert steps["algorithm"]["arguments"]["output_units"] == "kelvin"


##########################################
#
# DICT-BASED OVERRIDE TESTS
#
##########################################


def test_apply_step_override(sample_workflow):
    """Test recursive step overrides."""
    steps = deepcopy(sample_workflow["spec"]["steps"])

    override = {
        "reader": {
            "self_register": "LOW",
        }
    }

    result = workflows._apply_step_override(
        steps,
        override,
    )

    assert result["reader"]["arguments"]["self_register"] == "LOW"


def test_apply_step_override_missing_key(sample_workflow):
    """Test invalid override raises KeyError."""
    steps = deepcopy(sample_workflow["spec"]["steps"])

    override = {
        "missing_step": {
            "some_argument": "value",
        }
    }

    with pytest.raises(KeyError, match="Missing key"):
        workflows._apply_step_override(
            steps,
            override,
        )


def test_recursively_override(sample_workflow):
    """Test recursive overrides propagate into nested workflows."""
    steps = deepcopy(sample_workflow["spec"]["steps"])

    result = workflows._recursively_override(
        steps,
        "nested_workflow",
        "output_units",
        "kelvin",
        "algorithms",
    )

    nested = result["nested_workflow"]["spec"]["steps"]["nested_algorithm"]

    assert nested["arguments"]["output_units"] == "kelvin"


@pytest.mark.parametrize(
    "override_type,interface,expected",
    [
        ("globals", None, "kelvin"),
        ("kinds", "algorithms", "kelvin"),
        ("steps", None, "kelvin"),
    ],
)
def test_apply_override(
    sample_workflow,
    override_type,
    interface,
    expected,
):
    """Test all override application modes."""
    steps = deepcopy(sample_workflow["spec"]["steps"])

    result = workflows._apply_override(
        override_type,
        steps,
        "output_units",
        expected,
        interface,
    )

    assert result["algorithm"]["arguments"]["output_units"] == expected


def test_override_workflow_dict_format(
    sample_workflow,
):
    """Test dict-based workflow overrides."""
    workflow = deepcopy(sample_workflow)

    goverrides = {
        "satellite_zenith_angle_cutoff": 90,
    }

    koverrides = {
        "algorithms": {
            "output_units": "kelvin",
        }
    }

    soverrides = {
        "reader": {
            "self_register": "LOW",
        }
    }

    result = workflows._override_workflow_dict_format(
        workflow,
        goverrides=goverrides,
        koverrides=koverrides,
        soverrides=soverrides,
    )

    steps = result["spec"]["steps"]

    assert steps["reader"]["arguments"]["satellite_zenith_angle_cutoff"] == 90

    assert steps["algorithm"]["arguments"]["output_units"] == "kelvin"

    assert steps["reader"]["arguments"]["self_register"] == "LOW"


##########################################
#
# DETERMINE OVERRIDES TESTS
#
##########################################


@pytest.mark.parametrize(
    "goverrides,koverrides,soverrides,expected",
    [
        ({}, {}, {}, [None, None, None]),
        ({"a": 1}, {}, {}, ["globals", None, None]),
        ({}, {"a": 1}, {}, [None, "kinds", None]),
        ({}, {}, {"a": 1}, [None, None, "steps"]),
    ],
)
def test_determine_overrides_to_apply(
    goverrides,
    koverrides,
    soverrides,
    expected,
):
    """Test override selection logic."""
    result = workflows._determine_overrides_to_apply(
        goverrides,
        koverrides,
        soverrides,
    )

    assert result == expected
