# # # This source code is subject to the license referenced at
# # # https://github.com/NRLMMD-GEOIPS.

"""Pydantic models used to validate GeoIPS OBP v1 output-formatter plugins."""

# cspell:ignore TCWW
# cspel

# Python Standard Library
from typing import Any

# Third-Party Libraries
from pydantic import Field
from pyresample.geometry import AreaDefinition

# GeoIPS imports
from geoips.pydantic_models.v1.bases import PermissiveFrozenModel

PLUGIN_PROVIDED = "plugin_provided"


class OutputFormatterArgumentsModel(PermissiveFrozenModel):
    """Output-Formatter step argument definition.

    Pydantic model defining and validating Output Formatter step arguments.
    """

    # main_ax, map_obj, and fig are runtime generated states and are not provided
    # through Pydantic and must be populated during pre_call to ensure the plugin call
    # signature expecatations are met.
    append: bool = Field(
        False,
        description=(
            "When True, open the output file in append mode ('a') instead of write mode"
            "('w'). Automatically forced to True for every dataset beyond the first"
            "when multiple datasets are written to the same output file."
        ),
    )
    area_def: AreaDefinition | None = Field(
        None, description="The domain over which to read data."
    )
    # TASK: validate this to drop
    basedir: str = Field(
        PLUGIN_PROVIDED,
        description=(
            "Used to construct relative product paths in metadata output. Originally"
            " used to strip the TCWWW root path before replacing it with a public URL;"
            " now superseded by replace_geoips_paths() and no longer used across the"
            " entire implementation."
        ),
    )
    # used to render to background image
    # assign the bg_data dataset from the DataTree
    bg_data: Any | None = Field(None)
    bg_datatype_title: str | None = Field(None, description="background data type")
    bg_mpl_colors_info: dict[str, Any] | None = Field(
        None,
        description=("Matplotlib colormap configuration for the background dataset"),
    )
    bg_product_name_title: str | None = Field(
        None, description="Title of background product"
    )
    # used for constructing the title string to extract platform
    # do not remove this until after the 2026 GeoIPS workshop
    bg_xarray: Any | None = Field(None)
    # TASK: validate this to drop
    cog: bool = Field(
        True,
        description=(
            "Whether to produce a Cloud-Optimized GeoTIFF with internal overview"
            " levels. Currently this has no effect as overview generation is handled"
            " automatically by cog_translate() call."
        ),
    )
    clean_fname: str | None = Field(
        None,
        description=(
            "Output file path for a overlay-free elements such as no background"
            " imagery, coastlines, gridlines, title, or colorbar. When None, the clean"
            " image is skipped."
        ),
    )
    clobber: bool = Field(
        default=False,
        description="whether to overwrite the output file even if it exists",
    )
    # dead argument across all output_formatters where used
    # TASK: validate this to drop
    existing_image: str | None = Field(
        None,
        description=(
            "File path to a pre-rendered image onto which new data would be composited"
        ),
    )
    # Keep hist_colorbar and mpl_colors_info together for readability.
    # Do not reorder these fields as their proximity improves readability.
    hist_colorbar: bool = Field(
        PLUGIN_PROVIDED,
        description=(
            "Whether to display a histogram-enhanced colorbar instead of the standard"
            " colorbar. When True, replaces the standard colorbar with a combined"
            " colorbar and data-distribution histogram generated by hist_cmap()"
        ),
    )
    is_3d: bool = Field(
        False,
        description=(
            "When True, interpret the product data as a 3D array; otherwise,"
            "interpret it as a 2D array"
        ),
    )
    # TASK: validate this to optimize and then remove
    metadata_fname_dict: dict | None = Field(
        None,
        description=(
            "Dictionary of filename metadata passed to the metadata_tc_output_yaml."
            "Only the 'product_name' key is accessed to look the product plugin while"
            " computing coverage for TC metadata YAML output"
        ),
    )
    mpl_colors_info: dict[str, Any] | None = Field(
        None,
        description=(
            "Matplotlib colormap configuration dict generated by"
            " set_matplotlib_colors_standard(). The common keys include 'cmap', 'norm',"
            " 'cbar_label', and / or 'colorbar' (bool). \n When None, a default"
            " grayscale colormap spanning the data range is automatically generated."
            " Note: If 'hist_colorbar=True', the 'colorbar' flage is set to False to"
            " suppress the standard colorbar."
        ),
    )
    # TASK: validate this to drop
    # metadata_dir is used only in metadata_default.py and metadata_tc.py ouptut
    #  formatters and in both cases it is only referenced in call signature.
    metadata_dir: str = Field(
        "metadata",
        description=(
            "Subdirectory name for metadata; using non-default allows for"
            " non-operational outputs"
        ),
    )
    # 'output_dict' should be optimized and removed
    output_dict: dict | None = Field(
        None,
        description=(
            "Only 'product_spec_override' key is used to override the product"
            " specification used for coverage checking"
        ),
    )
    output_fname_dict: dict | None = Field(None)
    overwrite: bool = Field(
        True,
        description=("When False, skip writing the output file if it already exists."),
    )
    pressure_range_dict: dict | None = Field(None)
    product_datatype_title: str | None = Field(
        None,
        description="Display name for the data type in figure title.",
    )
    product_name_title: str | None = Field(
        None,
        description=(
            "Display name for the product shown in figure titles. When None,"
            " falls back to the product_name value"
        ),
    )
    # passed to save_image() which calls remove_duplicates() but the function is not
    # implemented (pass). This can be dropped during SSP -> OBP testing.
    remove_duplicate_minrange: Any | None = Field(None)
    # Used by only one 'unprojected_image.py', evaluate.
    savefig_kwargs: dict | None = Field(
        None,
        description=(
            "Extra keyword arguments to be used by matplotlib's savefif(). When None,"
            " defaults to an empty dict."
        ),
    )
    title_copyright: str | None = Field(None, description="copyright string")
    title_formatter: str | None = Field(None, description="format for title")
    use_compression: bool = Field(
        False,
        description=(
            "When True, apply zlib compression (level 5) to all variables when writing"
            " netCDF ouput."
        ),
    )
    var_name: str | None = Field(
        None,
        description=(
            "Variable name to extract from the xarray Dataset for plotting."
            "When None, falls back to product_name. Useful when the variable to plot"
            " differs from the product name."
        ),
    )
    x_size: int = Field(
        None,
        description=(
            "Number of pixels in the x direction of the projected area definition"
        ),
    )
    y_size: int = Field(
        None,
        description=(
            "Number of pixels in the y direction of the projected area definition"
        ),
    )
    # check with Jeremy and Mindy to see if windspeed_awips2_formatter.py
    # can be just defaulted to GEOIPS_OUTDIRS
    working_directory: str = Field(
        PLUGIN_PROVIDED,
        description=(
            "Base output directory for generated files, Defaults to GEOIPS_OUTDIRS"
        ),
    )
