Release Process:
- title: 'Add pip and mamba 1.14.3 environment files'
  description: |
    Note AMI TC test case failed due to geolocation, updated AMI unprojected image
    output due to minor differences at edge of scan.

    Package geoips_full
    Total run time 2671 seconds
    Number data types run 60
    Number data types failed 1
    Tue Dec 10 19:52:45 UTC 2024

    Package geoips_base
    Total run time 204 seconds
    Number data types run 3
    Number data types failed 0
    Mon Dec  9 21:32:04 UTC 2024
  files:
    added:
    - environments/mamba_base_package_list_1.14.3_20241209.yml
    - environments/pip_base_requirements_1.14.3_20241209.txt
    - environments/mamba_full_package_list_1.14.3_20241210.yml
    - environments/pip_full_requirements_1.14.3_20241210.txt
  date:
    start: 2024-12-09
    finish: 2024-12-10
  related-issue:
    internal: "GEOIPS/geoips#715 - 1.14.3 updates"
