$id: "geoips/schema/base"
type: object
required:
  - interface
  - metadata
  - spec
properties:
  interface:
    type: string
  metadata:
    type: object
    required: [name, family, short-description, long-description]
    properties:
      name:
        type: string
      family:
        type: string
      short-description:
        type: string
      long-description:
        type: string
