$id: product_inputs
$ref: base
title: "Product Inputs"
description: A list of products that can be produced from a specific data source.
type: object
required:
  - spec
properties:
  spec:
    type: object
    required:
      - products
    additionalProperties: false
    properties:
      products:
        minItems: 1
        type: array
        required:
          - name
          - variables
        properties:
          name:
            type: string
          variables:
            type: array
            minItems: 1
          default_overrides:
            type: object
            additionalProperties: true
