name: Build Docker Image

defaults:
  run:
    shell: bash

on:
  # Triggers when code is pushed to "main" branch
  # This should only happen when PRs are merged
  push:
    branches:
      - main

  # Triggers the workflow when pull request created and updated
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main

  # Triggers when a new release is created
  release:
    types:
      - published

  # Allows run of this workflow manually from the Actions tab
  workflow_dispatch:


env:
  REGISTRY: ghcr.io
  TEST_TAG: geoips:test

jobs:
  # create_variables:
  #   runs-on: ${{ vars.RUNNER }}
  #   steps:
  #     - name: Create image name
  #       run: |
  #         echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

  build_docker_image:
    runs-on: ${{ vars.RUNNER }}
    # Can't write to registry without this
    permissions:
      contents: read
      packages: write
    outputs:
      IMAGE_NAME: ${{ steps.set_image_nameoutputs.IMAGE_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup BuildX
        uses: docker/setup-buildx-action@v3

      - name: Set the image name
        id: set_image_name
        run: |
          image_name=${REGISTRY}/${GITHUB_REPOSITORY,,}
          echo "IMAGE_NAME=${image_name}" >> ${GITHUB_ENV}
          echo "IMAGE_NAME=${image_name}" >> ${GITHUB_OUTPUT}

      - name: Login to the Registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug
        run: |
          echo $PWD
          ls -la --color
          git status

      - name: Build and Push image
        uses: docker/build-push-action@v3.1.0
        with:
          context: .
          push: ${{ vars.GITHUB_REF_TYPE == 'tag' || vars.GITHUB_REF_NAME == 'main' }}
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }},test
          file: "Dockerfile"
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:test

  build_sphinx_html:
    runs-on: ${{ vars.RUNNER }}
    needs: build_docker_image
    container:
      image: ${{ needs.build_docker_image.outputs.IMAGE_NAME }}:${{ github.sha }}
    steps:
      - name: Debug location
        run: |
          echo $PWD
          ls -l --color

      - name: Install geoips documentation packages
        run: pip install -e .[doc]

      # - name: Download Docker image artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: docker-image
      #     path: .

      # - name: Load Docker Image
      #   run: docker load -i image.tar

      # # Include test dependencies to allow full documentation
      # - name: pip install geoips_default_branch[doc,test]
      #   run: |
      #     which pip
      #     pip uninstall -y geoips
      #     # Include test dependencies to allow full documentation
      #     pip install $PWD/geoips_default_branch[doc,test]
      #     ret=$?
      #     echo "${ret}"
      # - name: Checkout current repo current branch
      #   uses: actions/checkout@v3 # v3 is the latest for checkout
      #   with:
      #     fetch-depth: 0
      #     path: geoips_plugin_repo
      # - name: pip install geoips plugin repo
      #   run: |
      #     which pip
      #     curr_repo=`echo "$GITHUB_REPOSITORY" | sed "s,$GITHUB_REPOSITORY_OWNER/,,"`
      #     # We must reinstall even if this is the geoips repo, because we need to test
      #     # the current branch
      #     pip uninstall -y $curr_repo
      #     pip install -v $PWD/geoips_plugin_repo
      #     ret=$?
      #     echo "${ret}"
      # - name: create_plugin_registries
      #   run: |
      #     which create_plugin_registries
      #     create_plugin_registries
      #     ret=$?
      #     echo "${ret}"
      # - name: Run build html
      #   run: |
      #     echo "Build html docs"
      #     # Ie, get 'recenter_tc' out of 'NRLMMD-GEOIPS/recenter_tc'
      #     # using standard github actions variables
      #     curr_repo=`echo "$GITHUB_REPOSITORY" | sed "s,$GITHUB_REPOSITORY_OWNER/,,"`
      #     # Call build_docs.sh from the geoips default branch
      #     # Pass in
      #     #   the path to the current plugin repo,
      #     #   the name of the current repo,
      #     #   "html_only" to indicate producing only html output, and
      #     #   the path to the docs template directory in the geoips default branch.
      #     ./geoips_default_branch/docs/build_docs.sh ./geoips_plugin_repo $curr_repo html_only ./geoips_default_branch/docs
      #     ret=$?
      #     if [[ "${ret##*:}" != *"0"* ]]; then
      #       echo "::error::Building html docs ${ret##*:}"
      #       exit 1
      #     fi
