name: Build stable docker image

# 0. GEOIPS REPO ONLY - build latest docker image on all merges to default branch
#    * Plugin packages typically use latest image to ensure we have the most up to
#      date geoips infrastructure for the CI.
# 1. Tag and Release - on merge of v*-version-release
#    * Tag current version
#    * Release just tagged version
# 2. Package and Publish - on published release (from #1)
#    * Build wheel
#    * Publish to pypi
# 3. Deploy docs - on published release (from #1)
#    * pip install geoips
#    * pip install plugin repo
#    * build docs with geoips/docs/build_docs.sh
#    * deploy docs with geoips/docs/deploy_pages.sh
# 4. GEOIPS REPO ONLY - build stable docker image on published release (from #1)
#    * Stable image required for all plugin packages to use for CI
#    * doc-test workflow will fail on all plugin packages without stable image.

# reusable-build-docker-image is set up to build specifically the stable and latest images
# on the default branch and on tag/release.

on:
  # triggers the workflow on published release, this will build the 'stable' image
  release:
    types:
      - published
  # triggers the workflow on pushes to the default branch, this will build the 'latest' image
  push:
    branches:
      - main
  # allows run of this workflow manually from the actions tab
  # must be merged to default before it will be available to manually run.
  workflow_dispatch:

jobs:
  build-stable-image:
    name: Build stable docker image
    # You do not appear to be able to use variables in the "uses" field.
    # Note since this is run after merge to main, reusable-build-docker-image will
    # build the stable image specifically, which will subsequently be used by
    # the plugin packages.
    uses: NRLMMD-GEOIPS/geoips_ci/.github/workflows/reusable-build-docker-image.yaml@main
    permissions:
      contents: write
      packages: write
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      docker_token: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
