name: Run Brassy Command

on:
  workflow_dispatch:

jobs:
  run-brassy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Brassy
      run: |
        pip3 install brassy

    - name: Run Brassy on file
      run: |
        pwd && ls
