name: Build Sphinx pdf docs

defaults:
  run:
    shell: bash

# Can not use variables in the list of branches,
# GitHub Actions will not recognize, and workflow will not run.
on:
  # Triggers the workflow when pull request created and updated
  pull_request:
    branches:
      - main
  # Allows run of this workflow manually from the Actions tab
  # Must be merged to dev before it will be available to manually run.
  workflow_dispatch:

# conda command to install all the required libraries for installing geoips
# and geoips dependencies
#   openblas required for scipy
#   gcc/gxx required for akima/recenter_tc
#   latexcodec required for build_docs.sh
# conda create -y -n github_actions -c conda-forge gcc gxx openblas git latexcodec
jobs:
  build_sphinx_pdf:
    runs-on: ${{ vars.RUNNER }}
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4 # v4is the latest for setup-python
        with:
          python-version: "pypy-3.10" # I believe 3.10 is the latest for actions
          check-latest: true
      - name: Update pip
        run: pip install --upgrade pip
      - name: Checkout geoips repo default branch
        uses: actions/checkout@v3 # v3 is the latest for checkout
        with:
          fetch-depth: 0
          repository: ${{ vars.ORGANIZATION }}/geoips
          ref: ${{ vars.DEFAULT_BRANCH }}
          token: ${{ secrets.GEOIPS_TOKEN }}
          path: geoips_default_branch
      # Include test dependencies to allow full documentation
      - name: pip install geoips_default_branch[doc,test]
        run: |
          which pip
          pip uninstall -y geoips
          # Include test dependencies to allow full documentation
          pip install $PWD/geoips_default_branch[doc,test]
          ret=$?
          echo "${ret}"
      - name: Checkout current repo current branch
        uses: actions/checkout@v3 # v3 is the latest for checkout
        with:
          fetch-depth: 0
          path: geoips_plugin_repo
      - name: pip install geoips plugin repo
        run: |
          which pip
          curr_repo=`echo "$GITHUB_REPOSITORY" | sed "s,$GITHUB_REPOSITORY_OWNER/,,"`
          # Must reinstall even if this is the geoips repo - we must ensure we
          # are testing the current branch
          pip uninstall -y $curr_repo
          pip install -v $PWD/geoips_plugin_repo
          ret=$?
          echo "${ret}"
      - name: create_plugin_registries
        run: |
          which create_plugin_registries
          create_plugin_registries
          ret=$?
          echo "${ret}"
      - name: Run build pdf
        run: |
          echo "Build pdf docs"
          # Ie, get 'recenter_tc' out of 'NRLMMD-GEOIPS/recenter_tc'
          # using standard github actions variables.
          curr_repo=`echo "$GITHUB_REPOSITORY" | sed "s,$GITHUB_REPOSITORY_OWNER/,,"`
          # Call build_docs.sh from the geoips default branch
          # Pass in
          #   the path to the current plugin repo,
          #   the name of the current repo,
          #   "pdf_only" to indicate producing only pdf output, and
          #   the path to the docs template directory in the geoips default branch.
          ./geoips_default_branch/docs/build_docs.sh ./geoips_plugin_repo $curr_repo pdf_only ./geoips_default_branch/docs
          ret=$?
          if [[ "${ret##*:}" != *"0"* ]]; then
            echo "::error::Building pdf docs ${ret##*:}"
            exit 1
          fi
