name: Build Docker Image

defaults:
  run:
    shell: bash

on:
  # Triggers the workflow when pull request created and updated
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
  # Allows run of this workflow manually from the Actions tab
  workflow_dispatch:


env:
  REGISTRY: ghcr.io
  TEST_TAG: geoips:test

jobs:
  build_docker_image:
    runs-on: ${{ vars.RUNNER }}
    # Can't write to registry without this
    permissions:
      contents: read
      packages: write
    steps:
      # Need to make repository lowercase
      - name: Make image name
        shell: bash
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
      - name: Setup BuildX
        uses: docker/setup-buildx-action@v2
      - name: Login to the Registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build and Push image
        uses: docker/build-push-action@v3.1.0
        with:
          push: ${{ vars.GITHUB_REF_TYPE == 'tag' || vars.GITHUB_REF_NAME == 'main' }}
          tags: ghcr.io/${{ env.IMAGE_NAME }}:latest
          file: "Dockerfile"
          cache-from: type=registry,ref=ghcr.io/${{ env.IMAGE_NAME }}:latest