name: CI

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read
  packages: write

jobs:
  ci:
    uses: NRLMMD-GEOIPS/geoips_ci/.github/workflows/reusable-ci.yaml@main
    with:
      INPUT_TESTDATA_PATH: /data/geoips_outdirs
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      docker_token: ${{ secrets.DOCKER_TOKEN }}
