name: Integration Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: integ-test-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  integ-test:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.draft == false
    strategy:
      matrix:
        pip_editable: [true, false]
    name: integ-test (editable=${{ matrix.pip_editable }})
    uses: NRLMMD-GEOIPS/geoips_ci/.github/workflows/reusable-ci.yaml@main
    with:
      pip_editable: ${{ matrix.pip_editable }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      docker_token: ${{ secrets.DOCKER_TOKEN }}
