name: Integration Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read
  packages: write

jobs:
  integ-test:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.draft == false
    strategy:
      matrix:
        editable_pip_install: [true, false]
    concurrency:
      group: integ-test-${{ github.ref }}-${{ matrix.editable_pip_install }}
      cancel-in-progress: true
    name: integ-test (editable=${{ matrix.editable_pip_install }})
    uses: NRLMMD-GEOIPS/geoips_ci/.github/workflows/reusable-ci.yaml@fix-pip-editable
    with:
      editable_pip_install: ${{ matrix.editable_pip_install }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      docker_token: ${{ secrets.DOCKER_TOKEN }}
