name: lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
      - uses: jpetrucciani/bandit-check@master
        with:
          bandit_flags: '-ll'
