name: "Validate PR Checkboxes"

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  ensure-all-checkboxes-checked:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch PR body and validate checkboxes
        run: |
          # 1. Fetch the pull request body via GitHub API
          PR_BODY=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
          | jq -r .body)

          echo "Pull Request Body:"
          echo "$PR_BODY"

          # 2. Look for any unchecked boxes ("[ ]")
          UNCHECKED=$(echo "$PR_BODY" | grep '\[ \]' || true)

          # 3. If any are found, fail the build
          if [ -n "$UNCHECKED" ]; then
            echo "Error: Found unchecked checkboxes:"
            echo "$UNCHECKED"
            exit 1
          else
            echo "All checkboxes appear to be checked!"
          fi

