name: Push Docker Image

defaults:
  run:
    shell: bash

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  TEST_TAG: geoips:test

jobs:
  build_docker_image:
    runs-on: ${{ vars.RUNNER }}
    # Can't write to registry without this
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v2
        with:
          name: docker-image
          path: .

      - name: Load Docker Image
        run: docker load -i image.tar

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Need to make repository lowercase
      - name: Make image name
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Extract branch name
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request'
        run: |
          if [[ "${GITHUB_REF}" == refs/heads/* ]]; then
            echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == refs/pull/*/merge ]]; then
            echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF})" >> $GITHUB_ENV
          fi

      - name: Extract release tag
        if: github.event_name == 'release'
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> ${GITHUB_ENV}

      - name: Set Docker tags
        run: |
          # Set the DOCKER_TAGS environment variable based on the event
          # If the event is a release, use the release tag
          if [[ "${GITHUB_EVENT_NAME}" == "release" ]]; then
            echo "DOCKER_TAGS=${RELEASE_TAG},stable" >> $GITHUB_ENV
          # If the event is a push to main, use "latest"
          elif [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "DOCKER_TAGS=latest" >> $GITHUB_ENV
          # Otherwise, use the branch name
          else
            echo "DOCKER_TAGS=${GITHUB_SHA}" >> $GITHUB_ENV
          fi

      - name: Push Docker Image
        run: |
          # Push the Docker image to the GitHub Container Registry
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAGS }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAGS }}