name: Require up-to-date branch

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  status-check:
    runs-on: ${{ vars.RUNNER }}
    steps:
      - name: No-op status check
        run: echo "No-op Actions workflow to allow enforcing up to date branches before merge"
