name: Validate Pull Request
on: [pull_request]

jobs:
  changelog_is_changed:
    runs-on: ubuntu-22.04
    steps:
      - name: Ensure CHANGELOG.md is changed
        shell: bash
        run: |
          ret=$(git diff --name-only --diff-filter=M \
              ${GITHUB_BASE_REF}..${GITHUB_HEAD_REF} -- CHANGELOG.md)
          if [[ "${ret}" != "CHANGELOG.md" ]]; then
              echo "CHANGELOG.md has not been updated"
              exit 1
          fi